spring:
  profiles:
    active:
      - dev
  datasource:
    username: root
    password: pwd
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#to activate microservices to be discovered
  cloud:
    discovery:
      enabled: true
    #for microservices that interact with external microservices, this is to activate spring cloud circuit breaker resilience4j
    openfeign:
      circuitbreaker:
        enabled: true
# to indicate where services registration is running on
eureka:
  client:
    service-url:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://microservices-registration-service:8761/eureka/
