server:
  port: 8285
spring:
  application:
    name: clean-archi-business-service-project
  datasource:
#    url: jdbc:mysql://localhost:3306/projects-db?createDatabaseIfNotExist=true
    url: jdbc:mysql://microservices-db:3306/projects-db?createDatabaseIfNotExist=true
