server:
  port: 8282
spring:
  application:
    name: clean-archi-business-service-address
  datasource:
#    url: jdbc:mysql://localhost:3306/addresses-db?createDatabaseIfNotExist=true
    url: jdbc:mysql://microservices-db:3306/addresses-db?createDatabaseIfNotExist=true
