server:
  port: 8284
spring:
  application:
    name: clean-archi-business-service-company
  datasource:
#    url: jdbc:mysql://localhost:3306/companies-db?createDatabaseIfNotExist=true
    url: jdbc:mysql://microservices-db:3306/companies-db?createDatabaseIfNotExist=true
